# image
FROM oven/bun:latest

# where are we working
WORKDIR /app

# copy package json to directory
COPY ./package.json .

# install dependencies
RUN bun install

# copy all files in this directory to working directory inside container
COPY . .

# Copy the script into the container
COPY deployprod.sh /app/

# Make the script executable
RUN chmod +x /app/deployprod.sh

# some scripts
CMD [ "bun", "run", "dev"]
