services:

  frontend:
    build:
      context: ./frontend
    ports:
      - 3333:3333
    container_name: frontend-paleo3d
    stdin_open: true
    tty: true
    volumes:
      - ./data_bin:/app/data_bin
      - ./data_texture:/app/data_texture
    restart: unless-stopped