services:

  # ctexture:
  #   build:
  #     context: ./ctexture
  #   container_name: ctexture
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ../data_bin:/build/data_bin
  #     - ./output:/build/output
  #   #command: ["/bin/sh", "-c", "./bin/main"]
  
  gplates:
    build:
      context: ./gplates
    container_name: gplates
    stdin_open: true
    tty: true
    volumes:
      - ./outputg:/build/outputg
      - ./inputg:/build/inputg

